version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless
      - npm install -g serverless-python-requirements
      - npm install -g serverless-plugin-canary-deployments
  build:
    commands:
      - serverless deploy
